### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by ZexaZexaDubrovskiy** [ZexaZexaDubrovskiy/PMS#8]
Составить техническое задание проекта 3 февраля

**Comment by ZexaZexaDubrovskiy** [comment]
1. Убрать ЭП.
2. изменить таблицу с серверами(внизу ТЗ).
3. Сделать 2 уровневую связть таблицы и WPF приложения

**Comment by ZexaZexaDubrovskiy** [comment]
4. Отформатировать текст по СТП

**Comment by CreeptonIsReal** [comment]
[ТЗ_СУКС— Бригада 3.docx](https://github.com/ZexaZexaDubrovskiy/PMS/files/10768424/_.3.docx)
